apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartservice-default-deny
  namespace: smartservice
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartservice-api-allow
  namespace: smartservice
spec:
  podSelector:
    matchLabels:
      app: smartservice-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app: smartservice-ui
        - podSelector:
            matchLabels:
              app: smartservice-worker
      ports:
        - port: 8000
          protocol: TCP
        - port: 9090
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartservice-ui-allow
  namespace: smartservice
spec:
  podSelector:
    matchLabels:
      app: smartservice-ui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8501
          protocol: TCP
