apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartservice-api
  namespace: smartservice
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: smartservice-api
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
